Issue-035 :  About Us Cards
alahele/alahele pull request #36
Opened 2022-09-04 11:30 UTC by tineriver

Created cards to showcase our team and what Alahele is about.

2022-09-05 07:37 UTC, tineriver commented
close #<31>

2022-09-05 10:04 UTC, William-Liang808 requested changes

2022-09-13 03:28 UTC, William-Liang808 reviewed
Just need to remove Yong-Sung's name and should be good

2022-09-13 03:28 UTC, William-Liang808 commented on app/imports/ui/pages/Landing.jsx
> +                  <li>Yon-Sung Masuda</li>
LOL

2022-09-14 00:02 UTC, merged